name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master, develop]

jobs:

  unit-test:
    name: "Unit Test: core and app"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('/.gradle') }}-${{ hashFiles('/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Build
        run: ./gradlew assembleDebug
      - name: Test
        run: ./gradlew core:test
      - uses: actions/upload-artifact@v2
        with:
          name: app-play-debug.apk
          path: app/build/outputs/apk/play/debug/app-play-debug.apk
