name: CI Checks For LOG8371

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master, develop]

jobs:
  build:
    name: "Build App"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create temporary release keystore
        run: keytool -noprompt -genkey -v -keystore "app/keystore" -alias alias -storepass password -keypass password -keyalg RSA -validity 10 -dname "CN=antennapod.org, OU=dummy, O=dummy, L=dummy, S=dummy, C=US"
      - uses: gradle/gradle-build-action@v2
        name: Build
        with:
          gradle-version: wrapper
          arguments: assemble

  unit-test:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/gradle-build-action@v2
        name: Tests
        with:
          gradle-version: wrapper
          arguments: test

  emulator-test:
    name: "Emulator Tests"
    runs-on: macos-latest
    needs: build
    env:
      api-level: 27
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"

      - uses: gradle/gradle-build-action@v2
        name: Build with Gradle
        with:
          gradle-version: wrapper
          arguments: assemblePlayDebugAndroidTest

      - name: Cache AVD
        uses: actions/cache@v2
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ env.api-level }}
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - name: Android Emulator test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: zsh .github/workflows/runEmulatorTests.sh